### ISSUE TITLE
FR: Provide the ability to show businesses inside the radius

### ISSUE THREAD

**Issue by nthulke** [bronthulke/radius-checker#1]
If you could filter businesses inside that radius it would help to show what Grocery stores/restaurants are available.

**Comment by bronthulke** [comment]
Thanks for the suggestion, I'll look at adding this*!

*at the cost of an episode of Umbrella Academy tonight 😂

**Comment by bronthulke** [comment]
Just pointing out, this issue was resolved using Copilot Workspace 😄
